### ISSUE TITLE
Typedefinitions ts1046, ts1093 and ts2666

### ISSUE THREAD

**Issue by troepman** [lazywithclass/winston-cloudwatch#108]
Issue type: Bug

Hi,

Since version 2.0.6 our builds do not longer work with typescript 3.5.2 and are broken on the type file definition:
```
node_modules/winston-cloudwatch/typescript/winston-cloudwatch.d.ts:7:1 - error TS1046: Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.

7 class WinstonCloudWatch extends Transport {
  ~~~~~

node_modules/winston-cloudwatch/typescript/winston-cloudwatch.d.ts:40:55 - error TS1093:
Type annotation cannot appear on a constructor declaration.

40   constructor (options?: CloudwatchTransportOptions): WinstonCloudWatch;
                                                         ~~~~~~~~~~~~~~~~~

node_modules/winston-cloudwatch/typescript/winston-cloudwatch.d.ts:60:3 - error TS2666: Exports and export assignments are not permitted in module augmentations.

60   export  = WinstonCloudWatch;
     ~~~~~~


Found 3 errors.
```

Rolling back to 2.0.5 solves the problem for me.
Not a big deal for us right now but jus wanting to let you know.

With kind regards,

**Comment by lazywithclass** [comment]
Thanks for this, I will have a look.

**Comment by thomasviaud** [comment]
Hi, any ETA ?

**Comment by lazywithclass** [comment]
Hello, I don't have time for this at the moment, it's unlikely I will be able to have a look in the weekend but I'll try (leaving for vacation next week).

**Comment by troepman** [comment]
Hi, 

please have a look at #109 to see if this helps you out.

And of course have a great vacation!

kind regards,

**Comment by lazywithclass** [comment]
Fixed by @troepman PR https://github.com/lazywithclass/winston-cloudwatch/pull/109

Thanks again!
